### ISSUE TITLE
Add ClientID and ClientSecret to DB?

### ISSUE THREAD

**Issue by dvdgorila** [mileshenrichs/spotify-playlist-generator#2]
How do i add my clientID and ClientSecret to the script.db?

**Comment by mileshenrichs** [comment]
There's a great SQLite tutorial series here: https://www.youtube.com/watch?v=o-vsdfCBpsU&list=PLQVvvaa0QuDezJh0sC5CqXLKZTSKU1YNo

If you want to add your Client ID and secret to the database, here are the respective queries (if ``c`` is your database cursor):

``c.execute("INSERT INTO tokens VALUES ('client_id', 'your-client-id')")``
``c.execute("INSERT INTO tokens VALUES ('client_secret', 'your-client-secret')")``
And make sure to include ``conn.commit()`` afterwards to save these inserts.

As it's currently written in the script, however, I Base64-encoded a string in the form ``client_id:client_secret`` (per Spotify's instructions in step 2 [here](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow)), and saved this encoded string in _tokens_ with ``token_type`` = ``encoded_basic_token``.  You can see this being used in line 58, when I obtain a new access token.

**Comment by dvdgorila** [comment]
thanks much, I will give this a go.
